# Dart/Flutter Code Analysis Configuration
# 
# This file configures the Dart analyzer for the MuslimDeen Flutter project.
# It defines strict analysis settings, custom error handling, and linting rules
# to ensure high code quality, consistency, and maintainability.
# 
# The configuration emphasizes:
# - Strict type checking to catch runtime errors early
# - Detection of unused code to keep the codebase clean
# - Consistent code style and patterns
# - Early identification of potential issues

# Analyzer configuration
analyzer:
  # Exclude generated files from analysis
  # Add patterns for any generated code directories here
  # exclude:
  #   - 'lib/generated/**'  # Example: exclude generated files
  
  # Language mode settings for strict analysis
  language:
    # Enable strict type checking
    # This ensures all type casts are valid and catches type errors at compile time
    strict-casts: true
    
    # Enable strict inference
    # Forces the analyzer to infer types more strictly, reducing ambiguity
    strict-inference: true
    
    # Enable strict raw types
    # Prevents use of raw types (type parameters without bounds)
    strict-raw-types: true
  
  # Error severity configuration
  # These settings control how certain issues are reported by the analyzer
  errors:
    # Treat dead code as a warning to identify unreachable code paths
    # Dead code can indicate logic errors or forgotten code
    dead_code: warning
    
    # Report unused private declarations (classes, functions, variables)
    # Helps identify code that may have been forgotten during refactoring
    unused_element: warning
    
    # Report unused private instance fields
    # Unused fields increase memory usage and indicate incomplete refactoring
    unused_field: warning
    
    # Report unused imports
    # Unused imports increase bundle size and reduce code clarity
    unused_import: warning
    
    # Report unused local variables
    # Unused variables clutter the code and may indicate logic errors
    unused_local_variable: warning
    
    # Additional potentially useful rules (commented out for now):
    # unnecessary_null_comparison: warning  # Flag null comparisons that are always true/false
    # null_closures: warning               # Flag closures that don't handle null properly

# Linter configuration
# Defines linting rules to enforce code style and best practices
linter:
  rules:
    # Unused Code Related Rules
    # These rules help identify and eliminate dead code
    
    # Warn about unused constructor parameters
    # This helps identify constructors with parameters that aren't used
    - avoid_unused_constructor_parameters
    
    # Prefer final for fields that are never reassigned
    # This improves performance and makes the code more predictable
    - prefer_final_fields
    
    # Prefer final for local variables that are never reassigned
    # This prevents accidental reassignment and improves readability
    - prefer_final_locals
    
    # General Cleanliness Rules
    # These rules identify code that may contain hidden issues or bad practices
    
    # Flag unnecessary statements that don't affect program behavior
    - unnecessary_statements
    
    # Flag unnecessary lambda functions when a function reference would suffice
    - unnecessary_lambdas
    
    # Additional rules that could be enabled (commented out for now):
    # - unnecessary_parenthesis      # Flag unnecessary parentheses (can be stylistic)
    # - unnecessary_const           # Flag unnecessary const declarations
    # - unnecessary_new             # Flag unnecessary use of 'new' keyword
    
    # Code Quality Rules (consider adding these for stricter enforcement):
    # - always_declare_return_types  # Require explicit return types
    # - avoid_print                 # Disallow print statements in production code
    # - avoid_unnecessary_containers # Flag unnecessary widget nesting
    # - prefer_const_constructors    # Prefer const constructors where possible
    # - prefer_const_literals        # Prefer const for primitive values
    # - sized_box_for_whitespace     # Use SizedBox instead of Container for whitespace
    
    # Flutter-specific rules (uncomment if needed):
    # - use_key_in_widget_constructors  # Require keys for better widget identification
    # - prefer_single_quotes           # Use single quotes for consistency
    # - sort_child_properties_last     # Sort child properties to the end of widget lists

# Note on including external lint sets:
# For more comprehensive linting, consider including established rule sets:
#
# For Flutter projects, uncomment the following line:
# include: package:flutter_lints/flutter.yaml
#
# For pure Dart projects, uncomment the following line:
# include: package:lints/recommended.yaml
#
# These provide a good baseline of rules. The current configuration
# keeps things minimal and focused on the specific task of identifying
# unused code without pulling in external dependencies.