/// Zakat calculation and management models
/// 
/// This file defines comprehensive models for Zakat (Islamic almsgiving)
/// calculations, asset tracking, and educational information. Zakat is
/// one of the Five Pillars of Islam and represents the obligation for
/// Muslims to donate a fixed portion of their wealth to the poor.

/// Types of assets subject to Zakat calculation
/// 
/// Defines different categories of wealth that are subject to Zakat
/// according to Islamic jurisprudence. Each type has specific rules
/// for calculation, minimum thresholds (nisab), and distribution.
enum ZakatAssetType {
  /// Cash in hand and bank accounts
  /// Includes physical currency, savings accounts, checking accounts
  cash,
  
  /// Gold and gold jewelry
  /// Measured by weight, applies to both investment and personal use
  gold,
  
  /// Silver and silver items
  /// Measured by weight, less common in modern times
  silver,
  
  /// Stocks, shares, and investment portfolios
  /// Includes equity investments, mutual funds, and trading accounts
  stocks,
  
  /// Business inventory, equipment, and assets
  /// Includes merchandise, raw materials, and business property
  business,
  
  /// Livestock for breeding or trade
  /// Includes cattle, sheep, goats, and camels
  livestock,
  
  /// Agricultural produce and crops
  /// Includes harvests, fruits, and agricultural products
  agriculture,
  
  /// Other Zakatable assets not covered above
  /// Custom or special asset types
  other,
}

/// Zakat calculation result with complete breakdown
/// 
/// This model encapsulates the results of a Zakat calculation,
/// including the total amount due, asset breakdown, and comparison
/// with the nisab threshold. It provides comprehensive information
/// for understanding and fulfilling Zakat obligations.
/// 
/// Design principles:
/// - Immutable calculation result for audit trail
/// - Comprehensive asset breakdown for transparency
/// - Educational information for user understanding
/// - Support for multiple currencies and asset types
/// 
/// Key responsibilities:
/// - Store calculated Zakat amount and asset details
/// - Maintain nisab threshold comparison
/// - Provide formatted summary for display
/// - Support serialization for record keeping
/// 
/// Usage patterns:
/// - Generated by Zakat calculation engines
/// - Displayed in Zakat dashboard and reports
/// - Used for record keeping and compliance
/// - Shared with financial advisors for planning
class ZakatCalculation {
  /// Total value of all Zakatable assets
  /// Sum of all asset types subject to Zakat
  /// Used as the basis for Zakat calculation
  final double totalAssets;
  
  /// Total value of all liabilities and debts
  /// Subtracted from assets to determine net Zakatable wealth
  /// Includes loans, credit card debt, and other obligations
  final double totalLiabilities;
  
  /// Net Zakatable assets after subtracting liabilities
  /// Calculated as totalAssets - totalLiabilities
  /// This is the amount subject to Zakat calculation
  final double netAssets;
  
  /// Calculated Zakat amount due
  /// Typically 2.5% of net assets if above nisab threshold
  /// The amount that should be distributed to eligible recipients
  final double zakatAmount;
  
  /// Nisab threshold for this calculation
  /// Minimum wealth required before Zakat becomes due
  /// Based on current value of gold or silver
  final double nisabThreshold;
  
  /// Whether Zakat is due for this calculation
  /// True if netAssets meet or exceed nisabThreshold
  /// False if netAssets are below the minimum threshold
  final bool isZakatDue;
  
  /// Date when this calculation was performed
  /// Used for record keeping and validation purposes
  final DateTime calculationDate;
  
  /// Breakdown of assets by type
  /// Detailed breakdown of each asset category and its value
  /// Used for transparency and understanding of Zakat basis
  final Map<ZakatAssetType, double> assetBreakdown;
  
  /// Breakdown of liabilities by category
  /// Detailed breakdown of debts and obligations
  /// Used for transparency and validation of net assets
  final Map<String, double> liabilityBreakdown;

  /// Creates a new ZakatCalculation with complete calculation data
  /// 
  /// Parameters:
  /// - [totalAssets]: Total value of assets (required)
  /// - [totalLiabilities]: Total value of liabilities (required)
  /// - [netAssets]: Net Zakatable assets (required)
  /// - [zakatAmount]: Calculated Zakat due (required)
  /// - [nisabThreshold]: Minimum threshold (required)
  /// - [isZakatDue]: Whether Zakat is due (required)
  /// - [calculationDate]: When calculation was performed (required)
  /// - [assetBreakdown]: Asset breakdown by type (required)
  /// - [liabilityBreakdown]: Liability breakdown by category (required)
  const ZakatCalculation({
    required this.totalAssets,
    required this.totalLiabilities,
    required this.netAssets,
    required this.zakatAmount,
    required this.nisabThreshold,
    required this.isZakatDue,
    required this.calculationDate,
    required this.assetBreakdown,
    required this.liabilityBreakdown,
  });

  /// Calculates Zakat based on asset and liability data
  /// 
  /// Factory method that performs the actual Zakat calculation
  /// according to Islamic principles. Handles the 2.5% rate and
  /// nisab threshold comparison.
  /// 
  /// Parameters:
  /// - [assets]: Map of asset types to their values (required)
  /// - [liabilities]: Map of liability categories to their values (required)
  /// - [nisabThreshold]: Minimum wealth threshold (required)
  /// 
  /// Returns: ZakatCalculation with calculated results
  factory ZakatCalculation.calculate({
    required Map<ZakatAssetType, double> assets,
    required Map<String, double> liabilities,
    required double nisabThreshold,
  }) {
    final totalAssets = assets.values.fold(0.0, (sum, value) => sum + value);
    final totalLiabilities = liabilities.values.fold(
      0.0,
      (sum, value) => sum + value,
    );
    final netAssets = totalAssets - totalLiabilities;

    final isZakatDue = netAssets >= nisabThreshold;
    final zakatAmount =
        isZakatDue ? netAssets * 0.025 : 0.0; // 2.5% of net assets

    return ZakatCalculation(
      totalAssets: totalAssets,
      totalLiabilities: totalLiabilities,
      netAssets: netAssets,
      zakatAmount: zakatAmount,
      nisabThreshold: nisabThreshold,
      isZakatDue: isZakatDue,
      calculationDate: DateTime.now(),
      assetBreakdown: Map.from(assets),
      liabilityBreakdown: Map.from(liabilities),
    );
  }

  /// Gets a formatted summary of the Zakat calculation
  /// 
  /// Creates a human-readable summary of the calculation results,
  /// suitable for display in reports or dashboards.
  /// 
  /// Returns: Formatted multi-line string with calculation summary
  String getSummary() {
    final currency = 'USD'; // Could be made configurable
    return '''
Zakat Calculation Summary
═══════════════════════════
Total Assets: ${totalAssets.toStringAsFixed(2)} $currency
Total Liabilities: ${totalLiabilities.toStringAsFixed(2)} $currency
Net Assets: ${netAssets.toStringAsFixed(2)} $currency
Nisab Threshold: ${nisabThreshold.toStringAsFixed(2)} $currency

Zakat Due: ${isZakatDue ? 'Yes' : 'No'}
Zakat Amount: ${zakatAmount.toStringAsFixed(2)} $currency

Calculated on: ${calculationDate.toString().split(' ')[0]}
''';
  }

  @override
  String toString() {
    return 'ZakatCalculation(netAssets: $netAssets, zakatAmount: $zakatAmount, isDue: $isZakatDue)';
  }

  /// Serializes this ZakatCalculation to JSON for storage
  /// 
  /// Converts the calculation to a format suitable for persistent
  /// storage in databases or network transmission.
  /// 
  /// Returns: Map<String, dynamic> containing all calculation data
  Map<String, dynamic> toJson() {
    return {
      'totalAssets': totalAssets,
      'totalLiabilities': totalLiabilities,
      'netAssets': netAssets,
      'zakatAmount': zakatAmount,
      'nisabThreshold': nisabThreshold,
      'isZakatDue': isZakatDue,
      'calculationDate': calculationDate.toIso8601String(),
      'assetBreakdown': assetBreakdown.map(
        (key, value) => MapEntry(key.index.toString(), value),
      ),
      'liabilityBreakdown': liabilityBreakdown,
    };
  }
}

/// Zakat calculator input data model
/// 
/// This model represents the input data required for Zakat calculation,
/// including asset values, liabilities, and calculation parameters.
/// It serves as the data structure for user input and form handling.
/// 
/// Design principles:
/// - Comprehensive input structure for all asset types
/// - Support for multiple currencies
/// - Validation-friendly design
/// - Efficient serialization for storage
/// 
/// Usage patterns:
/// - Used in Zakat calculator forms and UI
/// - Stored for recurring calculation scenarios
/// - Shared between different calculation methods
class ZakatInput {
  /// Asset values by type
  /// Map of each asset category to its current value
  /// Used as the primary input for Zakat calculation
  final Map<ZakatAssetType, double> assets;
  
  /// Liability values by category
  /// Map of each liability category to its current amount
  /// Subtracted from assets to determine net wealth
  final Map<String, double> liabilities;
  
  /// Currency code for the calculation
  /// ISO 4217 currency code (e.g., 'USD', 'EUR', 'SAR')
  /// Used for display and nisab calculation
  final String currency;
  
  /// Nisab value for this calculation
  /// Minimum wealth threshold based on current market prices
  /// Typically calculated from gold or silver prices
  final double nisabValue;
  
  /// Date of last Zakat calculation
  /// Used to determine if a lunar year has passed
  /// Important for recurring Zakat obligations
  final DateTime lastCalculation;

  /// Creates a new ZakatInput with complete input data
  /// 
  /// Parameters:
  /// - [assets]: Asset values by type (required)
  /// - [liabilities]: Liability values by category (required)
  /// - [currency]: Currency code (defaults to 'USD')
  /// - [nisabValue]: Nisab threshold (required)
  /// - [lastCalculation]: Last calculation date (optional, defaults to now)
  /// 
  /// Notes:
  /// - lastCalculation defaults to current time if not provided
  /// - currency should be a valid ISO 4217 code
  /// - nisabValue should be calculated from current market prices
  ZakatInput({
    required this.assets,
    required this.liabilities,
    this.currency = 'USD',
    required this.nisabValue,
    DateTime? lastCalculation,
  }) : lastCalculation = lastCalculation ?? DateTime.now();

  /// Creates a ZakatInput from JSON data
  /// 
  /// Factory method for deserializing stored input data from
  /// databases or network sources.
  /// 
  /// Parameters:
  /// - [json]: Map containing serialized input data
  /// 
  /// Returns: New ZakatInput with restored data
  factory ZakatInput.fromJson(Map<String, dynamic> json) {
    return ZakatInput(
      assets: (json['assets'] as Map<String, dynamic>).map(
        (key, value) =>
            MapEntry(ZakatAssetType.values[int.parse(key)], value as double),
      ),
      liabilities: (json['liabilities'] as Map<String, dynamic>).map(
        (key, value) => MapEntry(key, value as double),
      ),
      currency: json['currency'] as String? ?? 'USD',
      nisabValue: json['nisabValue'] as double,
      lastCalculation: DateTime.parse(json['lastCalculation'] as String),
    );
  }

  /// Serializes this ZakatInput to JSON for storage
  /// 
  /// Converts the input data to a format suitable for persistent
  /// storage in databases or network transmission.
  /// 
  /// Returns: Map<String, dynamic> containing all input data
  Map<String, dynamic> toJson() {
    return {
      'assets': assets.map(
        (key, value) => MapEntry(key.index.toString(), value),
      ),
      'liabilities': liabilities,
      'currency': currency,
      'nisabValue': nisabValue,
      'lastCalculation': lastCalculation.toIso8601String(),
    };
  }

  /// Creates an empty ZakatInput with default values
  /// 
  /// Factory method for creating a default empty input
  /// for form initialization or testing purposes.
  /// 
  /// Returns: ZakatInput with empty assets and zero nisab
  factory ZakatInput.empty() {
    return ZakatInput(assets: {}, liabilities: {}, nisabValue: 0.0);
  }

  /// Checks if this input contains any data
  /// 
  /// Determines if the user has entered any asset or liability
  /// values, useful for form validation and UI state management.
  /// 
  /// Returns: true if any asset or liability has a non-zero value
  bool get hasData =>
      assets.values.any((value) => value > 0) ||
      liabilities.values.any((value) => value > 0);

  @override
  String toString() {
    return 'ZakatInput(assets: ${assets.length}, liabilities: ${liabilities.length}, currency: $currency)';
  }
}

/// Educational information about Zakat
/// 
/// This class provides comprehensive educational content about
/// Zakat, including calculation methods, asset types, and
/// Islamic legal principles. It serves as a reference for
/// users seeking to understand their Zakat obligations.
class ZakatInfo {
  /// Standard Zakat rate (2.5%)
  /// The percentage of net wealth due as Zakat
  static const double zakatRate = 0.025;
  
  /// Number of months in lunar year for Zakat calculation
  /// Zakat becomes due after one lunar year of ownership
  static const int lunarMonths = 12;

  /// Gets information about Zakat for different asset types
  /// 
  /// Provides detailed information about how Zakat applies to
  /// different types of assets, including calculation methods,
  /// nisab thresholds, and special considerations.
  /// 
  /// Parameters:
  /// - [type]: Asset type to get information for
  /// 
  /// Returns: Map containing detailed asset information
  static Map<String, String> getAssetTypeInfo(ZakatAssetType type) {
    switch (type) {
      case ZakatAssetType.cash:
        return {
          'title': 'Cash and Savings',
          'description': 'Cash in hand, bank accounts, money lent to others',
          'rate': '2.5% of total amount held for one lunar year',
          'nisab': 'Equivalent to 85g of gold or 595g of silver',
        };
      case ZakatAssetType.gold:
        return {
          'title': 'Gold and Jewelry',
          'description': 'Gold jewelry, coins, and bullion',
          'rate': '2.5% of value above Nisab threshold',
          'nisab': '85g of gold',
        };
      case ZakatAssetType.silver:
        return {
          'title': 'Silver',
          'description': 'Silver jewelry, coins, and items',
          'rate': '2.5% of value above Nisab threshold',
          'nisab': '595g of silver',
        };
      case ZakatAssetType.stocks:
        return {
          'title': 'Stocks and Investments',
          'description': 'Shares, bonds, and investment portfolios',
          'rate': '2.5% of current market value',
          'nisab': 'Based on cash equivalent value',
        };
      case ZakatAssetType.business:
        return {
          'title': 'Business Assets',
          'description': 'Inventory, equipment, and business investments',
          'rate': '2.5% of net business assets',
          'nisab': 'Standard Nisab threshold',
        };
      case ZakatAssetType.livestock:
        return {
          'title': 'Livestock',
          'description': 'Cattle, sheep, goats, camels for breeding',
          'rate': 'Varies by type and number',
          'nisab': '5 cattle, 40 sheep/goats, 5 camels',
        };
      case ZakatAssetType.agriculture:
        return {
          'title': 'Agricultural Produce',
          'description': 'Crops, fruits, and agricultural products',
          'rate': '5% or 10% depending on irrigation method',
          'nisab': '5 wasaq (approximately 653kg)',
        };
      case ZakatAssetType.other:
        return {
          'title': 'Other Assets',
          'description': 'Other Zakatable assets not covered above',
          'rate': '2.5% of value',
          'nisab': 'Standard Nisab threshold',
        };
    }
  }

  /// Gets general Zakat information
  /// 
  /// Provides comprehensive information about Zakat principles,
  /// purpose, timing, distribution, and importance.
  /// 
  /// Returns: Map containing general Zakat information
  static Map<String, String> getGeneralInfo() {
    return {
      'definition':
          'Zakat is one of the Five Pillars of Islam. It is obligatory almsgiving, intended to purify wealth and souls.',
      'purpose':
          'Zakat purifies wealth, promotes social welfare, reduces inequality, and fosters community solidarity.',
      'timing':
          'Zakat becomes obligatory when wealth reaches the Nisab threshold and has been held for one lunar year.',
      'distribution':
          'Zakat should be distributed to the eight categories mentioned in the Quran: the poor, orphans, widows, etc.',
      'importance':
          'Zakat is both a spiritual act and a social responsibility that strengthens the Muslim community.',
    };
  }

  /// Calculates Nisab threshold based on precious metal prices
  /// 
  /// Calculates the minimum wealth threshold required for Zakat
  /// to become due based on current market prices of gold or silver.
  /// 
  /// Parameters:
  /// - [goldPricePerGram]: Current market price of gold per gram
  /// - [silverPricePerGram]: Current market price of silver per gram
  /// - [useGold]: Whether to use gold (true) or silver (false) for calculation
  /// 
  /// Returns: Calculated nisab threshold in local currency
  static double calculateNisab({
    required double goldPricePerGram,
    required double silverPricePerGram,
    bool useGold = true,
  }) {
    if (useGold) {
      // Nisab is 85g of gold
      return 85.0 * goldPricePerGram;
    } else {
      // Alternative: 595g of silver
      return 595.0 * silverPricePerGram;
    }
  }

  /// Checks if one lunar year has passed since last Zakat payment
  /// 
  /// Determines if enough time has passed for Zakat to become
  /// due again based on the lunar calendar.
  /// 
  /// Parameters:
  /// - [lastPayment]: Date of last Zakat payment
  /// 
  /// Returns: true if one lunar year has passed, false otherwise
  static bool isZakatYearComplete(DateTime lastPayment) {
    final now = DateTime.now();
    final lunarYear = Duration(
      days: (lunarMonths * 29.5).round(),
    ); // Approximate lunar year
    return now.difference(lastPayment) >= lunarYear;
  }
}